# Generated by Django 6.0.2 on 2026-02-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medida',
            new_name='Medicao',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='unidade_medida',
            new_name='unidade_medidaid',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='medida',
            new_name='medicaoid',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='veiculo',
            new_name='veiculoid',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='marca',
            new_name='marcaid',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='marca',
            new_name='marcaid',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='modelo',
            new_name='modeloid',
        ),
    ]
